#!/usr/local/php/bin/php
<?php
	$func=substr(PHP_VERSION,0,1)>=7?'mark_func7':'mark_func';
	require '/usr/local/php/bin/'.$func;
	require 'markinit.php';
	$result='';
	if($argc>=2)
	{
		'-v'==$argv[1] && $result=markinit::$VERSION;
        'make'==$argv[1] && $result=markinit::make();
		'init'==$argv[1] && $result=genConfig(markinit::init());
	}
	echo $result.PHP_EOL;